site_name: Emuera.EM+EE ドキュメント
repo_url: https://gitlab.com/EvilMask/emuera.em.doc
site_url: https://evilmask.gitlab.io/emuera.em.doc/
extra_javascript:
  - javascripts/highlight.min.js
  - javascripts/erabasic-highlighths.min.js
extra_css:
  - css/eraBasic.min.css
theme:
  name: material
  highlightjs: false
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.expand
  palette: 
    - scheme: slate 
      primary: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
nav:
  - ホーム: README.md
  - リファレンス:
    - Reference/README.md
    - HTML系:
      - Reference/HTML_STRINGLEN.md
    - 文字列操作・参照:
      - Reference/REGEXPMATCH.md
    - 変数操作・変数参照・CSV参照:
      - Reference/ISDEFINED.md
      - Reference/EXISTVAR.md
      - Reference/ENUMFUNC.md
      - Reference/ENUMVAR.md
      - Reference/ENUMMACRO.md
      - Reference/GETSETVAR.md
      - Reference/VARSETEX.md
    - デバッグ補助・システムフロー制御:
      - Reference/QUIT_AND_RESTART.md
      - Reference/FORCE_QUIT.md
      - Reference/FORCE_QUIT_AND_RESTART.md
      - Reference/FORCE_BEGIN.md
    - 関数系（CALL等）:
      - Reference/EXISTFUNCTION.md
      - Reference/TRYCALLF.md
      - Reference/TRYCALLFORMF.md
    - 画像処理関連:
      - Reference/GDRAWTEXT.md
      - Reference/GGETFONT.md
      - Reference/GGETFONTSIZE.md
      - Reference/GGETFONTSTYLE.md
      - Reference/GGETTEXTSIZE.md
      - Reference/GDRAWGWITHROTATE.md
    - サウンド系:
      - Reference/PLAYSOUND.md
      - Reference/STOPSOUND.md
      - Reference/PLAYBGM.md
      - Reference/STOPBGM.md
      - Reference/EXISTSOUND.md
      - Reference/SETSOUNDVOLUME.md
      - Reference/SETBGMVOLUME.md
    - その他:
      - Reference/UPDATECHECK.md
      - Reference/GETMEMORYUSAGE.md
      - Reference/CLEARMEMORY.md
      

  - 変更ログ: Changelog/README.md
plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
  - i18n:
      default_language: ja
      languages:
        ja:
          name: 日本語
          build: true
        en:
          name: English
          build: true
          site_name: Emuera.EM+EE Document
        zh:
          name: 简体中文
          build: true
          site_name: Emuera.EM+EE 帮助文档
      nav_translations:
        zh:
          ホーム: 首页
          リファレンス: 参考手册
          変更ログ: 更新日志
        en:
          ホーム: Home
          リファレンス: Reference
          変更ログ: Changelog

markdown_extensions:
  # Python Markdown
  - meta
  - tables
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - admonition
  # Python Markdown Extensions
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.keys
